#lang play
(require "T1.rkt")
(print-only-errors #t)

#| Tests P1 b |#
;; Tests occurrences
(test (occurrences (varp "a") "b") 0)
(test (occurrences (varp "a") "a") 1)
(test (occurrences (notp (varp "a")) "b") 0)
(test (occurrences (notp (varp "a")) "a") 1)
(test (occurrences (andp (varp "a") (varp "b")) "c") 0)
(test (occurrences (andp (varp "a") (varp "b")) "a") 1)
(test (occurrences (andp (varp "a") (varp "a")) "a") 2)
(test (occurrences (orp (varp "a") (varp "b")) "c") 0)
(test (occurrences (orp (varp "a") (varp "b")) "a") 1)
(test (occurrences (orp (varp "a") (varp "a")) "a") 2)
(test (occurrences (orp (varp "a") (andp (varp "b") (notp (varp "c")))) "d") 0)
(test (occurrences (orp (varp "a") (andp (varp "b") (notp (varp "c")))) "a") 1)
(test (occurrences (orp (varp "a") (andp (varp "b") (notp (varp "a")))) "a") 2)
(test (occurrences (orp (varp "a") (andp (varp "a") (notp (varp "a")))) "a") 3)


#| Tests P1 c|#
;; Tests vars-rep
(test (vars-rep (varp "a")) (list "a"))
(test (vars-rep (notp (varp "a"))) (list "a"))
(test (vars-rep (andp (varp "a") (varp "b"))) (list "a" "b"))
(test (vars-rep (andp (varp "a") (varp "a"))) (list "a" "a"))
(test (vars-rep (orp (varp "a") (varp "b"))) (list "a" "b"))
(test (vars-rep (orp (varp "a") (varp "a"))) (list "a" "a"))
(test (vars-rep(orp (varp "a") (andp (varp "b") (notp (varp "c"))))) (list "a" "b" "c"))
(test (vars-rep(orp (varp "a") (andp (varp "b") (notp (varp "b"))))) (list "a" "b" "b"))
(test (vars-rep(orp (varp "c") (andp (varp "c") (notp (varp "c"))))) (list "c" "c" "c"))

;; Tests vars
(test (vars (varp "a")) (list "a"))
(test (vars (notp (varp "a"))) (list "a"))
(test (vars (andp (varp "a") (varp "b"))) (list "a" "b"))
(test (vars (andp (varp "a") (varp "a"))) (list "a"))
(test (vars (orp (varp "a") (varp "b"))) (list "a" "b"))
(test (vars (orp (varp "a") (varp "a"))) (list "a"))
(test (vars(orp (varp "a") (andp (varp "b") (notp (varp "c"))))) (list "a" "b" "c"))
(test (vars(orp (varp "a") (andp (varp "b") (notp (varp "b"))))) (list "a" "b"))
(test (vars(orp (varp "c") (andp (varp "c") (notp (varp "c"))))) (list "c"))


#| Tests P1 d |#
;; Tests add-var-to-env
(test (add-var-to-env "a" (list))
      (list (list (cons "a" #t))
            (list (cons "a" #f))))
(test (add-var-to-env "b" (list (cons "a" #t)))
      (list (list (cons "a" #t) (cons "b" #t))
            (list (cons "a" #t) (cons "b" #f))))
(test (add-var-to-env "c" (list (cons "a" #t) (cons "b" #t)))
      (list (list (cons "a" #t) (cons "b" #t) (cons "c" #t))
            (list (cons "a" #t) (cons "b" #t) (cons "c" #f))))
(test (add-var-to-env "c" (list (cons "a" #t) (cons "b" #f)))
      (list (list (cons "a" #t) (cons "b" #f) (cons "c" #t))
            (list (cons "a" #t) (cons "b" #f) (cons "c" #f))))
(test (add-var-to-env "c" (list (cons "a" #f) (cons "b" #t)))
      (list (list (cons "a" #f) (cons "b" #t) (cons "c" #t))
            (list (cons "a" #f) (cons "b" #t) (cons "c" #f))))
(test (add-var-to-env "c" (list (cons "a" #f) (cons "b" #f)))
      (list (list (cons "a" #f) (cons "b" #f) (cons "c" #t))
            (list (cons "a" #f) (cons "b" #f) (cons "c" #f))))

;; Tests add-var-to-env-list
(test (add-var-to-env-list "a" (list (list)))
      (list (list (cons "a" #t))
            (list (cons "a" #f))))
(test (add-var-to-env-list "b" (list (list (cons "a" #t))))
      (list (list (cons "a" #t) (cons "b" #t))
            (list (cons "a" #t) (cons "b" #f))))
(test (add-var-to-env-list "b" (list (list (cons "a" #f))))
      (list (list (cons "a" #f) (cons "b" #t))
            (list (cons "a" #f) (cons "b" #f))))
(test (add-var-to-env-list "b" (list (list (cons "a" #t))
                                     (list (cons "a" #f))))
      (list (list (cons "a" #t) (cons "b" #t))
            (list (cons "a" #t) (cons "b" #f))
            (list (cons "a" #f) (cons "b" #t))
            (list (cons "a" #f) (cons "b" #f))))
(test (add-var-to-env-list "c" (list (list (cons "a" #t) (cons "b" #t))
                                     (list (cons "a" #t) (cons "b" #f))
                                     (list (cons "a" #f) (cons "b" #t))
                                     (list (cons "a" #f) (cons "b" #f))))
      (list (list (cons "a" #t) (cons "b" #t) (cons "c" #t))
            (list (cons "a" #t) (cons "b" #t) (cons "c" #f))
            (list (cons "a" #t) (cons "b" #f) (cons "c" #t))
            (list (cons "a" #t) (cons "b" #f) (cons "c" #f))
            (list (cons "a" #f) (cons "b" #t) (cons "c" #t))
            (list (cons "a" #f) (cons "b" #t) (cons "c" #f))
            (list (cons "a" #f) (cons "b" #f) (cons "c" #t))
            (list (cons "a" #f) (cons "b" #f) (cons "c" #f))))

;; Tests add-var-list-to-env-list
(test (add-var-list-to-env-list (list) (list (list))) (list (list)))
(test (add-var-list-to-env-list (list) (list(list (cons "a" #t))
                                            (list (cons "a" #f))))
      (list (list (cons "a" #t))
            (list (cons "a" #f))))
(test (add-var-list-to-env-list (list "a") (list (list)))
      (list (list (cons "a" #t))
            (list (cons "a" #f))))
(test (add-var-list-to-env-list (list "b") (list (list (cons "a" #t))
                                                 (list (cons "a" #f))))
      (list (list (cons "a" #t) (cons "b" #t))
            (list (cons "a" #t) (cons "b" #f))
            (list (cons "a" #f) (cons "b" #t))
            (list (cons "a" #f) (cons "b" #f))))

;; Tests all-enviroments
(test (all-environments (list)) (list (list)))
(test (all-environments (list "a"))
      (list (list (cons "a" #t)) (list (cons "a" #f))))
(test (all-environments (list "a" "b"))
      (list (list (cons "a" #t) (cons "b" #t))
            (list (cons "a" #t) (cons "b" #f))
            (list (cons "a" #f) (cons "b" #t))
            (list (cons "a" #f) (cons "b" #f))))
(test (all-environments (list "a" "b" "c"))
      (list (list (cons "a" #t) (cons "b" #t) (cons "c" #t))
            (list (cons "a" #t) (cons "b" #t) (cons "c" #f))
            (list (cons "a" #t) (cons "b" #f) (cons "c" #t))
            (list (cons "a" #t) (cons "b" #f) (cons "c" #f))
            (list (cons "a" #f) (cons "b" #t) (cons "c" #t))
            (list (cons "a" #f) (cons "b" #t) (cons "c" #f))
            (list (cons "a" #f) (cons "b" #f) (cons "c" #t))
            (list (cons "a" #f) (cons "b" #f) (cons "c" #f))))


#| Tests P1 e |#
;; Tests eval
(test (eval (varp "a") (list (cons "a" #t))) #t)
(test (eval (varp "a") (list (cons "a" #f))) #f)
(test/exn (eval (varp "a") (list)) "variable a is not defined in environment")
(test/exn (eval (varp "a") (list (cons "b" #t))) "variable a is not defined in environment")

(test (eval (notp (varp "a")) (list (cons "a" #t))) #f)
(test (eval (notp (varp "a")) (list (cons "a" #f))) #t)
(test/exn (eval (notp (varp "a")) (list)) "variable a is not defined in environment")
(test/exn (eval (notp (varp "a")) (list (cons "b" #t))) "variable a is not defined in environment")

(test (eval (andp (varp "a") (varp "a")) (list (cons "a" #t) (cons "b" #t))) #t)
(test (eval (andp (varp "a") (varp "b")) (list (cons "a" #t) (cons "b" #t))) #t)
(test (eval (andp (varp "a") (varp "b")) (list (cons "a" #t) (cons "b" #f))) #f)
(test (eval (andp (varp "a") (varp "b")) (list (cons "a" #f) (cons "b" #t))) #f)
(test (eval (andp (varp "a") (varp "b")) (list (cons "a" #f) (cons "b" #f))) #f)
(test/exn (eval (andp (varp "a") (varp "b")) (list (cons "b" #t))) "variable a is not defined in environment")
(test/exn (eval (andp (varp "a") (varp "b")) (list (cons "a" #t))) "variable b is not defined in environment")
(test/exn (eval (andp (varp "a") (varp "b")) (list)) "variable a is not defined in environment")
(test/exn (eval (andp (varp "a") (varp "b")) (list (cons "c" #t) (cons "d" #t))) "variable a is not defined in environment")

(test (eval (orp (varp "a") (varp "a")) (list (cons "a" #t) (cons "b" #t))) #t)
(test (eval (orp (varp "a") (varp "b")) (list (cons "a" #t) (cons "b" #t))) #t)
(test (eval (orp (varp "a") (varp "b")) (list (cons "a" #t) (cons "b" #f))) #t)
(test (eval (orp (varp "a") (varp "b")) (list (cons "a" #f) (cons "b" #t))) #t)
(test (eval (orp (varp "a") (varp "b")) (list (cons "a" #f) (cons "b" #f))) #f)
(test/exn (eval (orp (varp "a") (varp "b")) (list (cons "b" #t))) "variable a is not defined in environment")
(test/exn (eval (orp (varp "a") (varp "b")) (list (cons "a" #t))) "variable b is not defined in environment")
(test/exn (eval (orp (varp "a") (varp "b")) (list)) "variable a is not defined in environment")
(test/exn (eval (orp (varp "a") (varp "b")) (list (cons "c" #t) (cons "d" #t))) "variable a is not defined in environment")

(test (eval (orp (varp "a") (andp (varp "a") (notp (varp "a")))) (list (cons "a" #t))) #t)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #t) (cons "b" #t) (cons "c" #t))) #t)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #t) (cons "b" #t) (cons "c" #f))) #t)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #t) (cons "b" #f) (cons "c" #t))) #t)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #t) (cons "b" #f) (cons "c" #f))) #t)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #f) (cons "b" #t) (cons "c" #t))) #f)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #f) (cons "b" #t) (cons "c" #f))) #t)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #f) (cons "b" #f) (cons "c" #t))) #f)
(test (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #f) (cons "b" #f) (cons "c" #f))) #f)
(test/exn (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "b" #t) (cons "c" #t))) "variable a is not defined in environment")
(test/exn (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #t) (cons "c" #t))) "variable b is not defined in environment")
(test/exn (eval (orp (varp "a") (andp (varp "b") (notp (varp "c")))) (list (cons "a" #t) (cons "b" #t))) "variable c is not defined in environment")

